### ISSUE TITLE
Version 1.30 does not decompress Brotli codec whereas 1.28 does

### ISSUE THREAD

**Issue by VTol-zz** [aloneguid/ironcompress#15]
X64 Windows 10 .NET 7, this LINQPad code:

var bytes = File.ReadAllBytes(@"...\bytes.bin");
var iron = new Iron();
using (var ironCompressResult = iron.Decompress(Codec.Brotli, bytes))
{
	ironCompressResult.Dump();
	Encoding.UTF8.GetString(ironCompressResult).Dump();
}

Then ironCompressResult.Length = 0 for 1.30 version, but ironCompressResult.Length > 0 for 1.28 (which works as expected).

I tried .NET 7, .NET 6 and netstandard 2.0, the same result.

**Comment by aloneguid** [comment]
Decompression requires result length (third parameter in `Decompress` method). It shouldn't be optional which is a typo in the interface.

**Comment by VTol-zz** [comment]
All right, adding it solves the issue. But 1) it is a bit confusing, why the result length parameter is not needed when decompressing in 1.28 version (unintentional regression?); 2) there is no exception indicating the decompression actually did not perform at all.

**Comment by aloneguid** [comment]
You would still get the same error when targeting .net standard 2.0 (i.e. running under classic .net framework, not .net core). Brotli does not store length attribute, but due to the fact 1.28 was trying managed decoder first, which has some magic to decode without length by wasting memory, that worked. 1.30 is reversing the logic by using native decoder first, as it's always faster and more efficient, and only then trying managed if not available (i.e. when running on unsupported hardware or web assembly). Managed decoders can be 5 times slower than native hence the reason to do that. Also .net standard 2.0 does not have managed brotli available, but .net core does, so even if you target .net standard 2.0 but run under .net core you will have managed decoder.

Error handling will be improved in next releases, thanks for raising the issue.

**Comment by VTol-zz** [comment]
Now I understand the version difference mystery! Thank you for detailed explanation!
